# Generated by Django 4.0 on 2021-12-20 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='phone_number',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
