# Generated by Django 4.0 on 2021-12-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
