# Generated by Django 4.0 on 2021-12-20 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_alert_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
