# Generated by Django 4.0 on 2021-12-19 21:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.station')),
            ],
        ),
    ]
