# Generated by Django 4.0 on 2021-12-20 16:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transports', '0001_initial'),
        ('users', '0002_alter_utilisateur_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_time', models.TimeField(default=django.utils.timezone.now)),
                ('alert_day', models.DateField(default=django.utils.timezone.now)),
                ('alert_votes', models.IntegerField(default=0)),
                ('alert_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.line')),
                ('alert_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.station')),
                ('alert_whistleblower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='AlertVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('UP', 'upvote'), ('DO', 'downvote')], default='UP', max_length=2)),
                ('vote_timestamp', models.DateTimeField(auto_now=True)),
                ('vote_remark', models.TextField(blank=True, null=True)),
                ('alert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.alert')),
                ('vote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.utilisateur')),
            ],
        ),
    ]
