# Generated by Django 4.0 on 2021-12-19 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='alert_whistleblower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.utilisateur'),
        ),
    ]
