# Generated by Django 4.0 on 2021-12-20 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_alertvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertvote',
            name='vote_type',
            field=models.CharField(choices=[('UP', 'upvote'), ('DO', 'downvote')], default='UP', max_length=2),
        ),
    ]
