# Generated by Django 4.0 on 2021-12-20 16:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Line_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('Line_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicule_type', models.CharField(choices=[('B', 'Bus'), ('T', 'Tram'), ('M', 'Metro'), ('N', 'Noctis')], default='B', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station_name', models.CharField(max_length=200)),
                ('Station_adress', models.CharField(max_length=300)),
                ('Station_vehicule', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transports.vehicule')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_desc', models.TextField()),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.line')),
            ],
        ),
        migrations.CreateModel(
            name='Line_station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.station')),
            ],
        ),
        migrations.AddField(
            model_name='line',
            name='Line_vehicule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='transports.vehicule'),
        ),
    ]
