# Generated by Django 4.0 on 2021-12-20 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='Line_vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.vehicule'),
        ),
        migrations.AlterField(
            model_name='station',
            name='Station_vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.vehicule'),
        ),
    ]
