# Generated by Django 4.0 on 2021-12-20 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
    ]
