# Generated by Django 4.0 on 2021-12-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='vehicule',
        ),
        migrations.AddField(
            model_name='line',
            name='vehicule_type',
            field=models.CharField(choices=[('B', 'Bus'), ('T', 'Tram'), ('M', 'Metro'), ('N', 'Noctis')], default='B', max_length=1),
        ),
    ]
