# Generated by Django 4.0 on 2021-12-20 01:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_remove_line_vehicule_line_vehicule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='Line_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
