# Generated by Django 4.0 on 2021-12-20 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_alter_line_line_name_alter_line_line_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='Line_stations',
            field=models.ManyToManyField(through='transports.Route', to='transports.Station', verbose_name='Arrêts associés'),
        ),
        migrations.AlterField(
            model_name='line',
            name='Line_vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.vehicule', verbose_name='Type de transport'),
        ),
        migrations.AlterField(
            model_name='route',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.line', verbose_name='Ligne associée'),
        ),
        migrations.AlterField(
            model_name='route',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.station', verbose_name='Arrêt associé'),
        ),
        migrations.AlterField(
            model_name='station',
            name='Station_vehicule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transports.vehicule', verbose_name='Type de transport'),
        ),
    ]
