# Generated by Django 4.0 on 2021-12-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0003_alter_line_line_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='Line_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
