# Generated by Django 4.0 on 2021-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_station_station_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='Station_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
