# Generated by Django 4.0 on 2021-12-20 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0004_line_line_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='vehicule_type',
            field=models.CharField(choices=[('B', 'Bus'), ('T', 'Tram'), ('M', 'Metro')], default='B', max_length=1),
        ),
    ]
