# Generated by Django 4.0 on 2021-12-20 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0002_alter_line_line_vehicule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='Line_stations',
            field=models.ManyToManyField(to='transports.Station'),
        ),
    ]
