# Generated by Django 4.0 on 2021-12-20 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0006_station_station_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_desc',
        ),
        migrations.AddField(
            model_name='route',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='station',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='transports.station'),
            preserve_default=False,
        ),
    ]
