# Generated by Django 4.0 on 2021-12-20 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transports', '0007_remove_route_route_desc_route_order_route_station'),
    ]

    operations = [
    ]
